//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDomainTest.Domain1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.WorkflowStatus = new HashSet<WorkflowStatus>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentAreaId { get; set; }
        public string AreaName { get; set; }
        public string Strasse { get; set; }
        public string Postfach { get; set; }
        public int Plz { get; set; }
        public string Ort { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Homepage { get; set; }
        public string Notiz { get; set; }
    
        public virtual ICollection<WorkflowStatus> WorkflowStatus { get; set; }
    }
}
