//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDomainTest.Domain1
{
    using System;
    using System.Collections.Generic;
    
    public partial class County
    {
        public int Id { get; set; }
        public string CountyIso { get; set; }
        public string CountyName { get; set; }
    }
}
